version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - postgres_network  # Add backend to the same network as postgres

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - backend
    networks:
      - postgres_network  # Add frontend to the same network as well (optional)

volumes:
  postgres_data:

networks:
  postgres_network:  # Define the network explicitly
    driver: bridge